# __OBTENCION DE DATOS__

## __La base de datos de la canasta basica rural y urbana abarca un periodo desde el 2001 hasta enero del 2025__

## la obtencion de los datos fue a travez de tecnicas de web scraping y la consulta de diversos sitios web ya que la descarga directa de los sitios oficiales no era directamente en algun formato .csv , ni formato .xls y no se trataban tampoco de algun archivo Excel nativo, sino un archivo en formato HTML con tablas que Excel puede abrir, pero no es un verdadero archivo de Excel. Esto explicaba por qué al querer abrirlo en Jupyter Notebook se mostraba código HTML en lugar de datos tabulares.

___

### Los datos de "La Canasta Basica Alimentaria de El Salvador rural" fueron obtenidos del sitio web de la OFICINA NACIONAL DEL ESTADISTICA Y CENSO DE EL SALVADOR (ONEC-BCR)

### *https://onec.bcr.gob.sv/ipc_consulta/ipc_dat.asp*

In [11]:
from bs4 import BeautifulSoup
import pandas as pd
import io  # Importar StringIO

# Cargar el archivo como texto
with open("download (1).xls", "r", encoding="utf-8") as f:
    html_content = f.read()

# Parsear el contenido HTML con BeautifulSoup
soup = BeautifulSoup(html_content, "html.parser")

# Extraer todas las tablas
tables = soup.find_all("table")

# Convertir la primera tabla en un DataFrame 
df = pd.read_html(io.StringIO(str(tables[0])))[0]

# Mostrar los primeros registros
df.head()

# Guardar en CSV 
#df.to_csv("canasta_basica_rural .csv", index=False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,AÑO,ARTÍCULO,GRAMOS POR PERSONA,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL
1,AÑO,ARTÍCULO,GRAMOS POR PERSONA,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
2,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001
3,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
4,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300

___

### Los datos de "La Canasta Basica Alimentaria de El Salvador rural" fueron obtenidos del sitio web de la OFICINA NACIONAL DEL ESTADISTICA Y CENSO DE EL SALVADOR (ONEC-BCR)

### *https://onec.bcr.gob.sv/ipc_consulta/ipc_dat.asp*

In [12]:
from bs4 import BeautifulSoup
import pandas as pd
import io  # Importar StringIO

# Cargar el archivo 
with open("download (1).xls", "r", encoding="utf-8") as f:
    html_content = f.read()

# Pasar el contenido HTML con BeautifulSoup
soup = BeautifulSoup(html_content, "html.parser")

# Extraer todas las tablas
tables = soup.find_all("table")

# Convertir la primera tabla en un DataFrame 
df = pd.read_html(io.StringIO(str(tables[0])))[0]

# Mostrar los primeros registros
df.head()

# Guardar en CSV 
#df.to_csv("canasta_basica_urbana .csv", index=False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,AÑO,ARTÍCULO,GRAMOS POR PERSONA,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL
1,AÑO,ARTÍCULO,GRAMOS POR PERSONA,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
2,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001
3,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
4,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300

___

# __LIMPIEZA DE LOS DATOS__

# <ins> CANASTA BASICA RURAL </ins>

In [14]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural .csv")

# Mostrar las primeras filas
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,AÑO,ARTÍCULO,GRAMOS POR PERSONA,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL
1,AÑO,ARTÍCULO,GRAMOS POR PERSONA,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
2,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001
3,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
4,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300

In [15]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural .csv")

# Eliminar filas innecesarias
df = df.drop([0, 2], axis=0).reset_index(drop=True)

# Mostrar las primeras filas
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,AÑO,ARTÍCULO,GRAMOS POR PERSONA,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
1,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
2,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
3,2001,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
4,2001,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200

In [39]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural .csv")

# Eliminar filas innecesarias
df = df.drop([0, 1, 2], axis=0).reset_index(drop=True)
df.index = range(1, len(df) + 1)

# Convertir las columnas de enero a diciembre a tipo numérico y redondear a 2 decimales
meses = ['3','4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14']

# Asegurar que los valores sean numéricos y redondear
#df[meses] = df[meses].apply(pd.to_numeric, errors='coerce')

# RENOMBRANDO LAS COLUMNAS
df.rename(columns={
    '0':'AÑO',
    '1': 'ARTICULO',
    '2': 'GRAMOS POR PERSONAS',
    '3': 'ENERO',
    '4': 'FEBRERO',
    '5': 'MARZO',
    '6': 'ABRIL',
    '7': 'MAYO',
    '8': 'JUNIO',
    '9': 'JULIO',
    '10': 'AGOSTO',
    '11': 'SEPTIEMBRE',
    '12': 'OCTUBRE',
    '13': 'NOVIEMBRE',
    '14': 'DICIEMBRE' },
          inplace=True)

# Mostrar las primeras filas
df.head(17)

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
1,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
2,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
3,2001,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
4,2001,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
5,2001,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
6,2001,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
7,2001,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
8,2001,Frijoles,60,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0600,0.0600,0.0700,0.0600
9,2001,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
10,2001,Costo diario por persona,0,0.5900,0.6000,0.6000,0.6000,0.5900,0.6000,0.6100,0.6200,0.6200,0.6200,0.6200,0.6100
11,2001,más 10% (cocción),0,0.6500,0.6600,0.6600,0.6600,0.6500,0.6600,0.6700,0.6800,0.6800,0.6800,0.6800,0.6700
12,2001,Costo diario por familia de 4.84 miembros,0,3.1500,3.1900,3.1900,3.1900,3.1500,3.1900,3.2400,3.2900,3.2900,3.2900,3.2900,3.2400
13,2001,Costo mensual por familia**,0,94.5000,95.7000,95.7000,95.7000,94.5000,95.7000,97.2000,98.7000,98.7000,98.7000,98.7000,97.2000
14,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002
15,2002,Tortillas,402,0.3200,0.2900,0.3000,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900
16,2002,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
17,2002,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600

In [40]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural .csv")

# Eliminar filas innecesarias
df = df.drop([0, 1, 2], axis=0).reset_index(drop=True)
df.index = range(1, len(df) + 1)

# Convertir las columnas de enero a diciembre a tipo numérico y redondear a 2 decimales
meses = ['3','4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14']

# Asegurar que los valores sean numéricos y redondear
#df[meses] = df[meses].apply(pd.to_numeric, errors='coerce')

# RENOMBRANDO LAS COLUMNAS
df.rename(columns={
    '0':'AÑO',
    '1': 'ARTICULO',
    '2': 'GRAMOS POR PERSONAS',
    '3': 'ENERO',
    '4': 'FEBRERO',
    '5': 'MARZO',
    '6': 'ABRIL',
    '7': 'MAYO',
    '8': 'JUNIO',
    '9': 'JULIO',
    '10': 'AGOSTO',
    '11': 'SEPTIEMBRE',
    '12': 'OCTUBRE',
    '13': 'NOVIEMBRE',
    '14': 'DICIEMBRE' },
          inplace=True)

#df = df.drop([12, 13, 14, 15], axis=0).reset_index(drop=True)
#df.index = range(1, len(df) + 1)

# LIMPIEZA DE FILAS NO NECESARIAS
#n = 16  # Cada cuántas filas se repite
#df = df.drop(df.index[11::n])# Elimina cada n-ésima fila


df.to_csv("canasta_basica_rural_1 DEPURACION.csv", index=False, encoding="utf-8-sig")

df.head(24)

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
1,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
2,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
3,2001,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
4,2001,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
5,2001,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
6,2001,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
7,2001,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
8,2001,Frijoles,60,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0600,0.0600,0.0700,0.0600
9,2001,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
10,2001,Costo diario por persona,0,0.5900,0.6000,0.6000,0.6000,0.5900,0.6000,0.6100,0.6200,0.6200,0.6200,0.6200,0.6100
11,2001,más 10% (cocción),0,0.6500,0.6600,0.6600,0.6600,0.6500,0.6600,0.6700,0.6800,0.6800,0.6800,0.6800,0.6700
12,2001,Costo diario por familia de 4.84 miembros,0,3.1500,3.1900,3.1900,3.1900,3.1500,3.1900,3.2400,3.2900,3.2900,3.2900,3.2900,3.2400
13,2001,Costo mensual por familia**,0,94.5000,95.7000,95.7000,95.7000,94.5000,95.7000,97.2000,98.7000,98.7000,98.7000,98.7000,97.2000
14,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002
15,2002,Tortillas,402,0.3200,0.2900,0.3000,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900
16,2002,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
17,2002,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
18,2002,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
19,2002,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
20,2002,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
21,2002,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
22,2002,Frijoles,60,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0500
23,2002,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
24,2002,Costo diario por persona,0,0.6200,0.6000,0.6000,0.6000,0.6000,0.5900,0.5900,0.5900,0.5900,0.5900,0.5900,0.5800

# SEGUNDA DEPURACION

In [41]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural_1 DEPURACION.csv")

# Generar la lista de índices a eliminar
costo_diario_por_persona = list(range(22, 372, 15))  
#coccion = list(range(23, 372, 15))  
#celda_24 = list(range(24, 372, 15))  # costo diario por familia
#celda_25 = list(range(25, 372, 15))  # costo mensual por familia

# Combinar todas las listas
indices_a_eliminar = costo_diario_por_persona + coccion + celda_24 + celda_25

# Eliminar las filas del DataFrame
df = df.drop(indices_a_eliminar, errors='ignore').reset_index(drop=True)

df.index = range(1, len(df) + 1)

df.to_csv("canasta_basica_rural_2 DEPURACION.csv", index=False, encoding="utf-8-sig")

# Mostrar las primeras 60 filas para verificar
df.head(60)

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
1,2001,Tortillas,402,0.30,0.30,0.30,0.31,0.30,0.31,0.32,0.32,0.32,0.31,0.31,0.30
2,2001,Arroz,39,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
3,2001,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
4,2001,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
5,2001,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
6,2001,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
7,2001,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
8,2001,Frijoles,60,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.07,0.06
9,2001,Azúcar,65,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
10,2001,Costo diario por persona,0,0.59,0.60,0.60,0.60,0.59,0.60,0.61,0.62,0.62,0.62,0.62,0.61
11,2001,más 10% (cocción),0,0.65,0.66,0.66,0.66,0.65,0.66,0.67,0.68,0.68,0.68,0.68,0.67
12,2001,Costo diario por familia de 4.84 miembros,0,3.15,3.19,3.19,3.19,3.15,3.19,3.24,3.29,3.29,3.29,3.29,3.24
13,2001,Costo mensual por familia**,0,94.50,95.70,95.70,95.70,94.50,95.70,97.20,98.70,98.70,98.70,98.70,97.20
14,2002,2002,2002,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00
15,2002,Tortillas,402,0.32,0.29,0.30,0.29,0.29,0.29,0.29,0.29,0.29,0.29,0.29,0.29
16,2002,Arroz,39,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
17,2002,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
18,2002,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
19,2002,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
20,2002,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
21,2002,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
22,2002,Frijoles,60,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.05
23,2002,Costo mensual por familia**,0,96.60,93.60,93.60,93.60,93.60,92.10,92.10,92.10,92.10,92.10,92.10,90.90
24,2003,2003,2003,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00,2003.00
25,2003,Tortillas,402,0.29,0.29,0.29,0.29,0.29,0.30,0.30,0.31,0.32,0.31,0.32,0.31
26,2003,Arroz,39,0.03,0.03,0.03,0.03,0.03,0.04,0.04,0.04,0.04,0.04,0.03,0.03
27,2003,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
28,2003,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
29,2003,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.07
30,2003,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
31,2003,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
32,2003,Frijoles,60,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05
33,2003,Azúcar,65,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
34,2004,2004,2004,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00,2004.00
35,2004,Tortillas,402,0.31,0.30,0.30,0.31,0.31,0.33,0.35,0.34,0.36,0.34,0.34,0.33
36,2004,Arroz,39,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
37,2004,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
38,2004,Grasas 2 _ /,14,0.03,0.03,0.03,0.02,0.02,0.03,0.03,0.03,0.03,0.03,0.03,0.03
39,2004,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.07,0.07,0.07
40,2004,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
41,2004,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
42,2004,Frijoles,60,0.05,0.05,0.05,0.05,0.06,0.06,0.07,0.07,0.08,0.09,0.08,0.07
43,2004,Azúcar,65,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
44,2004,Costo diario por persona,0,0.62,0.61,0.61,0.62,0.63,0.64,0.67,0.67,0.69,0.69,0.68,0.66
45,2005,Tortillas,402,0.34,0.34,0.33,0.33,0.34,0.34,0.34,0.34,0.32,0.35,0.34,0.34
46,2005,Arroz,39,0.04,0.04,0.04,0.03,0.03,0.03,0.04,0.04,0.04,0.04,0.04,0.04
47,2005,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.07,0.07,0.07
48,2005,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
49,2005,Huevos,30,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
50,2005,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
51,2005,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
52,2005,Frijoles,60,0.08,0.07,0.07,0.07,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08
53,2005,Azúcar,65,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05
54,2005,Costo diario por persona,0,0.68,0.68,0.67,0.67,0.68,0.68,0.69,0.68,0.67,0.70,0.69,0.69
55,2005,más 10% (cocción),0,0.75,0.75,0.74,0.74,0.75,0.75,0.76,0.75,0.74,0.77,0.76,0.76
56,2006,Arroz,39,0.04,0.04,0.03,0.03,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
57,2006,Carnes 1_ /,14,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
58,2006,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
59,2006,Huevos,30,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
60,2006,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02

In [42]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural_1 DEPURACION.csv")

# Generar la lista de índices a eliminar
#costo_diario_por_persona = list(range(22, 372, 15))  
#coccion = list(range(23, 372, 15))  
#celda_24 = list(range(24, 372, 15))  # costo diario por familia
#celda_25 = list(range(25, 372, 15))  # costo mensual por familia

# Combinar todas las listas
indices_a_eliminar = costo_diario_por_persona + coccion + celda_24 + celda_25

# Eliminar las filas del DataFrame
#df = df.drop(indices_a_eliminar, errors='ignore').reset_index(drop=True)

df.index = range(1, len(df) + 1)

df.to_csv("canasta_basica_rural_REVISION.csv", index=False, encoding="utf-8-sig")

# Mostrar las primeras 60 filas para verificar
df.head(22)

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
1,2001,Tortillas,402,0.30,0.30,0.30,0.31,0.30,0.31,0.32,0.32,0.32,0.31,0.31,0.30
2,2001,Arroz,39,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
3,2001,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
4,2001,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
5,2001,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
6,2001,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
7,2001,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
8,2001,Frijoles,60,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.07,0.06
9,2001,Azúcar,65,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
10,2001,Costo diario por persona,0,0.59,0.60,0.60,0.60,0.59,0.60,0.61,0.62,0.62,0.62,0.62,0.61
11,2001,más 10% (cocción),0,0.65,0.66,0.66,0.66,0.65,0.66,0.67,0.68,0.68,0.68,0.68,0.67
12,2001,Costo diario por familia de 4.84 miembros,0,3.15,3.19,3.19,3.19,3.15,3.19,3.24,3.29,3.29,3.29,3.29,3.24
13,2001,Costo mensual por familia**,0,94.50,95.70,95.70,95.70,94.50,95.70,97.20,98.70,98.70,98.70,98.70,97.20
14,2002,2002,2002,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00,2002.00
15,2002,Tortillas,402,0.32,0.29,0.30,0.29,0.29,0.29,0.29,0.29,0.29,0.29,0.29,0.29
16,2002,Arroz,39,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
17,2002,Carnes 1_ /,14,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
18,2002,Grasas 2 _ /,14,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
19,2002,Huevos,30,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
20,2002,Leche Fluida *,31,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
21,2002,Frutas 3_ /,16,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
22,2002,Frijoles,60,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.05

In [35]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("canasta_basica_rural_1 DEPURACION.csv")

# Generar la lista de índices a eliminar
#costo_diario_por_persona = list(range(22, 372, 15))  
#coccion = list(range(23, 372, 15))  
#celda_24 = list(range(24, 372, 15))  # costo diario por familia
#celda_25 = list(range(25, 372, 15))  # costo mensual por familia

# Combinar todas las listas
indices_a_eliminar = costo_diario_por_persona + coccion + celda_24 + celda_25

# Eliminar las filas del DataFrame
#df = df.drop(indices_a_eliminar, errors='ignore').reset_index(drop=True)
#df.index = range(1, len(df) + 1)

# Guardar en un nuevo archivo CSV asegurando que los valores se mantengan sin redondeo
df.to_csv("canasta_basica_rural_2 DEPURACION.csv", index=False, encoding="utf-8-sig", float_format="%.4f")

# Verificar si los valores se mantienen correctamente después de la eliminación y conversión
df.head(60)  # Muestra las primeras 60 filas

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
0,AÑO,ARTÍCULO,GRAMOS POR PERSONA,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL,RURAL
1,AÑO,ARTÍCULO,GRAMOS POR PERSONA,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
2,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001
3,2001,Tortillas,402,0.3000,0.3000,0.3000,0.3100,0.3000,0.3100,0.3200,0.3200,0.3200,0.3100,0.3100,0.3000
4,2001,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
5,2001,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
6,2001,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
7,2001,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
8,2001,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
9,2001,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
10,2001,Frijoles,60,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0600,0.0600,0.0700,0.0600
11,2001,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
12,2001,Costo diario por persona,0,0.5900,0.6000,0.6000,0.6000,0.5900,0.6000,0.6100,0.6200,0.6200,0.6200,0.6200,0.6100
13,2001,más 10% (cocción),0,0.6500,0.6600,0.6600,0.6600,0.6500,0.6600,0.6700,0.6800,0.6800,0.6800,0.6800,0.6700
14,2001,Costo diario por familia de 4.84 miembros,0,3.1500,3.1900,3.1900,3.1900,3.1500,3.1900,3.2400,3.2900,3.2900,3.2900,3.2900,3.2400
15,2001,Costo mensual por familia**,0,94.5000,95.7000,95.7000,95.7000,94.5000,95.7000,97.2000,98.7000,98.7000,98.7000,98.7000,97.2000
16,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002
17,2002,Tortillas,402,0.3200,0.2900,0.3000,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900,0.2900
18,2002,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
19,2002,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
20,2002,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
21,2002,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
22,2002,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
23,2002,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
24,2002,Frijoles,60,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0500
25,2002,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
26,2002,Costo diario por persona,0,0.6200,0.6000,0.6000,0.6000,0.6000,0.5900,0.5900,0.5900,0.5900,0.5900,0.5900,0.5800
27,2002,más 10% (cocción),0,0.6800,0.6600,0.6600,0.6600,0.6600,0.6500,0.6500,0.6500,0.6500,0.6500,0.6500,0.6400
28,2002,Costo diario por familia de 4.73 miembros,0,3.2200,3.1200,3.1200,3.1200,3.1200,3.0700,3.0700,3.0700,3.0700,3.0700,3.0700,3.0300
29,2002,Costo mensual por familia**,0,96.6000,93.6000,93.6000,93.6000,93.6000,92.1000,92.1000,92.1000,92.1000,92.1000,92.1000,90.9000
30,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003
31,2003,Tortillas,402,0.2900,0.2900,0.2900,0.2900,0.2900,0.3000,0.3000,0.3100,0.3200,0.3100,0.3200,0.3100
32,2003,Arroz,39,0.0300,0.0300,0.0300,0.0300,0.0300,0.0400,0.0400,0.0400,0.0400,0.0400,0.0300,0.0300
33,2003,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
34,2003,Grasas 2 _ /,14,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
35,2003,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0700
36,2003,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
37,2003,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
38,2003,Frijoles,60,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500,0.0500
39,2003,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
40,2003,Costo diario por persona,0,0.5900,0.5900,0.5900,0.5800,0.5900,0.6000,0.6000,0.6100,0.6200,0.6200,0.6200,0.6200
41,2003,más 10% (cocción),0,0.6500,0.6500,0.6500,0.6400,0.6500,0.6600,0.6600,0.6700,0.6800,0.6800,0.6800,0.6800
42,2003,Costo diario por familia de 4.52 miembros,0,2.9400,2.9400,2.9400,2.8900,2.9400,2.9800,2.9800,3.0300,3.0700,3.0700,3.0700,3.0700
43,2003,Costo mensual por familia**,0,88.2000,88.2000,88.2000,86.7000,88.2000,89.4000,89.4000,90.9000,92.1000,92.1000,92.1000,92.1000
44,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004
45,2004,Tortillas,402,0.3100,0.3000,0.3000,0.3100,0.3100,0.3300,0.3500,0.3400,0.3600,0.3400,0.3400,0.3300
46,2004,Arroz,39,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
47,2004,Carnes 1_ /,14,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600
48,2004,Grasas 2 _ /,14,0.0300,0.0300,0.0300,0.0200,0.0200,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300,0.0300
49,2004,Huevos,30,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0600,0.0700,0.0700,0.0700
50,2004,Leche Fluida *,31,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200
51,2004,Frutas 3_ /,16,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
52,2004,Frijoles,60,0.0500,0.0500,0.0500,0.0500,0.0600,0.0600,0.0700,0.0700,0.0800,0.0900,0.0800,0.0700
53,2004,Azúcar,65,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400,0.0400
54,2004,Costo diario por persona,0,0.6200,0.6100,0.6100,0.6200,0.6300,0.6400,0.6700,0.6700,0.6900,0.6900,0.6800,0.6600
55,2004,más 10% (cocción),0,0.6800,0.6700,0.6700,0.6800,0.6900,0.7000,0.7400,0.7400,0.7600,0.7600,0.7500,0.7300
56,2004,Costo diario por familia de 4.52 miembros,0,3.0700,3.0300,3.0300,3.0700,3.1200,3.1600,3.3400,3.3400,3.4400,3.4400,3.3900,3.3000
57,2004,Costo mensual por familia**,0,92.1000,90.9000,90.9000,92.1000,93.6000,94.8000,100.2000,100.2000,103.2000,103.2000,101.7000,99.0000
58,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005
59,2005,Tortillas,402,0.3400,0.3400,0.3300,0.3300,0.3400,0.3400,0.3400,0.3400,0.3200,0.3500,0.3400,0.3400

# TERCERA DEPURACION

In [44]:
import pandas as pd

# Cargar el archivo CSV
DF = pd.read_csv("canasta_basica_rural_2 DEPURACION.csv")
DF = DF.reset_index(drop=True)  # Corregido: debe ser DF, no df
DF.index = range(1, len(DF) + 1)

# Ruta para guardar el archivo CSV
ruta_guardado = r"C:\Users\alvar\OneDrive\Escritorio\PROYECTO FINAL\DATA SET\canasta_basica_rural_PREPROCESADO.csv"

# Guardar el DataFrame 'DF' en la ruta especificada
DF.to_csv(ruta_guardado, index=False, encoding="utf-8-sig")

print("Archivo guardado correctamente en:", ruta_guardado)

Archivo guardado correctamente en: C:\Users\alvar\OneDrive\Escritorio\PROYECTO FINAL\DATA SET\canasta_basica_rural_PREPROCESADO.csv

In [45]:
import pandas as pd

# Cargar el archivo CSV
DF = pd.read_csv(r"C:\Users\alvar\OneDrive\Escritorio\PROYECTO FINAL\DATA SET\canasta_basica_rural_PREPROCESADO.csv")
DF

,AÑO,ARTICULO,GRAMOS POR PERSONAS,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
0,2001,Tortillas,402,0.3000,0.30,0.30,0.31,0.30,0.31,0.32,0.32,0.32,0.31,0.31,0.30
1,2001,Arroz,39,0.0300,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
2,2001,Carnes 1_ /,14,0.0600,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
3,2001,Grasas 2 _ /,14,0.0200,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
4,2001,Huevos,30,0.0600,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2025,Azúcar,65,0.0748,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
257,2025,Costo diario por persona,0,1.2802,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
258,2025,más 10% (cocción),0,1.4082,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
259,2025,Costo diario por familia de 4.26 miembros,0,5.9990,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
260,2025,Costo mensual por familia**,0,179.9692,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00